# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Pwn9.com - Blog
description: > # this means to ignore newlines until "baseurl:"
  Pwn9.com Gaming Community 
  Blog Posts
#baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.pwn9.com" # the base hostname & protocol for your site
twitter_username: pwn9
github_username:  pwn9
permalink: /:year/:month/:title

# Build settings
exclude:
  - LICENSE.adoc
  - README.adoc
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - vendor

theme: jekyll-theme-slate